nordvpn_username: ""
nordvpn_password: ""
nordvpn_connect: United_States
vpn_container_ports: []
vpn_container_net_local: 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
vpn_container_net6_local: fe80::/10
vpn_container_selfheal_enabled: true
