- name: qbittorrent container
  docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    entrypoint:
      - /usr/bin/qbittorrent-nox
    restart_policy: unless-stopped
    network_mode: container:{{ qbittorrent_vpn_container }}
    memory: "{{ qbittorrent_memory_limit }}"
    env: "{{ qbittorrent_env }}"
    volumes:
      - "{{ qbittorrent_config_dir }}:/config"
      - "{{ qbittorrent_data_dir }}:/data"

- name: qbittorrent exporter container
  docker_container:
    name: qbittorrent-exporter
    image: esanchezm/prometheus-qbittorrent-exporter
    restart_policy: unless-stopped
    env: "{{ qbittorrent_exporter_env }}"
    ports:
      - 0.0.0.0:{{ qbittorrent_exporter_port }}:8000
      - "[::]:{{ qbittorrent_exporter_port }}:8000"

- name: copy selfheal task list for qbittorrent
  template:
    src: selfheal.yml.j2
    dest: /etc/selfheal/tasks/qbittorrent.yml
  when: qbittorrent_selfheal_enabled
- name: remove selfheal task for qbittorrent
  file:
    path: /etc/selfheal/tasks/qbittorrent.yml
    state: absent
  when: not qbittorrent_selfheal_enabled
