- name: config directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ pvr_volumes_dir }}/jackett-config'
    - '{{ pvr_volumes_dir }}/radarr-config'
    - '{{ pvr_volumes_dir }}/sonarr-config'
- name: flairsolverr container
  docker_container:
    name: flairsolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart_policy: unless-stopped
    network_mode: container:{{ pvr_vpn_container }}
- name: jackett container
  docker_container:
    name: jackett
    image: lscr.io/linuxserver/jackett
    restart_policy: unless-stopped
    network_mode: container:{{ pvr_vpn_container }}
    env:
      PUID: '33'
      PGID: '33'
      TZ: America/New_York
    volumes:
      - '{{ pvr_volumes_dir }}/jackett-config:/config'
- name: sonarr container
  docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr
    restart_policy: unless-stopped
    links:
      - '{{ pvr_vpn_container }}:jackett'
    ports:
      - 0.0.0.0:8989:8989
      - '[::]:8989:8989'
    env:
      PUID: '0'
      PGID: '0'
    volumes:
      - '{{ pvr_volumes_dir }}/sonarr-config:/config'
      - '{{ pvr_data_dir }}:/data'
- name: radarr container
  docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr
    restart_policy: unless-stopped
    links:
      - '{{ pvr_vpn_container }}:jackett'
    ports:
      - 0.0.0.0:7878:7878
      - '[::]:7878:7878'
    env:
      PUID: '0'
      PGID: '0'
    volumes:
      - '{{ pvr_volumes_dir }}/radarr-config:/config'
      - '{{ pvr_data_dir }}:/data'
- name: lidarr container
  docker_container:
    name: lidarr
    image: lscr.io/linuxserver/lidarr
    restart_policy: unless-stopped
    links:
      - '{{ pvr_vpn_container }}:jackett'
    ports:
      - 0.0.0.0:8686:8686
      - '[::]:8686:8686'
    env:
      PUID: '0'
      PGID: '0'
    volumes:
      - '{{ pvr_volumes_dir }}/lidarr-config:/config'
      - '{{ pvr_data_dir }}:/data'

- name: copy selfheal task list for pvr
  copy:
    src: selfheal.yml
    dest: /etc/selfheal/tasks/pvr.yml
  when: pvr_selfheal_enabled
- name: remove selfheal task for pvr
  file:
    path: /etc/selfheal/tasks/pvr.yml
    state: absent
  when: not pvr_selfheal_enabled
