- systemd:
    name: docker.service
    state: started
- docker_container:
    comparisons:
      "*": ignore
    name: watchtower
- docker_container:
    comparisons:
      "*": ignore
    name: cadvisor
