- name: install rsync
  apt:
    state: present
    name: rsync

- name: copy rsync-backup.service
  template:
    src: rsync-backup.service.j2
    dest: /etc/systemd/system/rsync-backup.service
  notify:
    - restart rsync-backup service

- name: copy rsync-backup.timer
  template:
    src: rsync-backup.timer.j2
    dest: /etc/systemd/system/rsync-backup.timer
  notify:
    - restart rsync-backup timer

- meta: flush_handlers

- name: enable systemd timer
  systemd:
    name: rsync-backup.timer
    state: started
    enabled: yes
    daemon_reload: yes
  ignore_errors: "{{ ansible_check_mode }}"
